#!/usr/bin/env python3
"""make_seam_s5.py — the simple channel through a lens that holds A5 but not PSL(2,7).

The seam (Conway / KT, det = 1) has a perfect derived subgroup (Δ=1), so every
non-abelian image is perfect — and the smallest perfect groups are the simple
ones.  Its aperture (the non-abelian simple groups it surjects onto) is
{A5, PSL(2,7)}.  Through GL(3,2) the door is PSL(2,7) = the whole group (and
GL(3,2) IS simple).  Through A5 the door is A5 = the whole group (A5 IS simple).

S5 is the discriminating lens for the *simple channel*: it holds A5 (order 60,
even permutations) as a proper subgroup, but PSL(2,7) has order 168 which does
not divide |S5| = 120, so PSL(2,7) is absent.  And S5 itself is NOT simple
(S5' = A5).  So the aperture ∩ lattice test is:

    aperture {A5, PSL(2,7)}  ∩  lattice of S5 {A5, S4, A4, ...} = {A5}

If the seam's read at S5 is exactly the A5 room — a PROPER subgroup — and it does
NOT fill the whole S5, then "the whole, or not at all" is really "the simple
subgroup the lens holds, or not at all": the seam fills the simple room, and
refuses the non-simple whole.  One rule for both rooms.

Run:  python3 make_seam_s5.py     (n=4 counts ~2 min each)
"""
import itertools
from collections import Counter

import numpy as np

from make_seam_profile import fixed_points
from make_seam_why import subgroup_order


# ---- S5 as tables -----------------------------------------------------------
def perm_mul(p, q):
    return tuple(p[q[i]] for i in range(len(p)))


def perm_inv(p):
    r = [0] * len(p)
    for i in range(len(p)):
        r[p[i]] = i
    return tuple(r)


def perm_order(p):
    n = len(p)
    seen = [False] * n
    o = 1
    for i in range(n):
        if not seen[i]:
            j = i
            l = 0
            while not seen[j]:
                seen[j] = True
                j = p[j]
                l += 1
            o = o * l // __import__("math").gcd(o, l)
    return o


def build_S5():
    """(size, mul, inv, conj, order) tables for S5, all permutations of 5."""
    elems = [p for p in itertools.permutations(range(5))]
    idx = {e: i for i, e in enumerate(elems)}
    size = len(elems)
    ident = idx[tuple(range(5))]
    mul = np.zeros((size, size), dtype=np.int64)
    for a in range(size):
        for b in range(size):
            mul[a, b] = idx[perm_mul(elems[a], elems[b])]
    inv = np.zeros(size, dtype=np.int64)
    for a in range(size):
        for b in range(size):
            if mul[a, b] == ident:
                inv[a] = b
    conj = np.zeros((size, size), dtype=np.int64)
    for a in range(size):
        for b in range(size):
            conj[a, b] = mul[mul[a, b], inv[a]]
    order = np.zeros(size, dtype=np.int64)
    for a in range(size):
        order[a] = perm_order(elems[a])
    return size, mul, inv, conj, order


def subgroup_closure(gens, size, mul, inv, ident):
    H = {ident}
    frontier = [ident]
    for g in gens:
        if g not in H:
            H.add(g)
            frontier.append(g)
    while frontier:
        a = frontier.pop()
        for b in gens:
            for c in (mul[a, b], mul[b, a], inv[b]):
                if c not in H:
                    H.add(c)
                    frontier.append(c)
    return sorted(H)


def classify(elems, size, mul, inv, ident, order):
    """Classify the subgroup generated by elems (indices) by order + structure."""
    H = subgroup_closure(elems, size, mul, inv, ident)
    o = len(H)
    if o == 1:
        return "1"
    abelian = all(mul[a, b] == mul[b, a] for a in H for b in H)
    hist = Counter(int(order[x]) for x in H)
    if o == 2:
        return "Z2"
    if o == 3:
        return "Z3"
    if o == 4:
        return "Z4" if hist.get(4, 0) == 2 else "Z2^2"
    if o == 5:
        return "Z5"
    if o == 6:
        return "Z6" if abelian else "S3"
    if o == 8:
        return "D8" if hist.get(4, 0) else "Z2^3"
    if o == 10:
        return "D5"
    if o == 12:
        return "A4" if hist.get(3, 0) == 8 else "D12"
    if o == 20:
        return "F20"
    if o == 24:
        return "S4"
    if o == 60:
        return "A5"
    if o == 120:
        return "S5"
    return f"ord{o}"


def reach(word, n, size, mul, inv, conj, ident, order):
    """Return {subgroup_name: count} over the seam's fixed points."""
    fps = fixed_points(word, n, size, mul, inv, conj)
    by = Counter()
    for X in fps:
        so = subgroup_order(list(X), mul, inv, ident)
        if so == 1:
            continue
        by[classify(list(X), size, mul, inv, ident, order)] += 1
    return by, len(fps)


NONABEL = ("Z2", "Z3", "Z4", "Z5", "Z6", "Z2^2", "Z2^3", "1")


def show(reach_by):
    nonabel = {k: v for k, v in reach_by.items() if k not in NONABEL}
    abel = {k: v for k, v in reach_by.items() if k in NONABEL}
    print("    non-abelian image subgroups:")
    for k in sorted(nonabel, key=lambda s: (len(s), s)):
        print(f"      {k:<6} count={nonabel[k]}")
    print("    abelian/cyclic images:", dict(sorted(abel.items())))


def main():
    size, mul, inv, conj, order = build_S5()
    ident = int(np.where(order == 1)[0][0])
    print("|S5| =", size, "= 2^3·3·5 ; element orders",
          dict(sorted(Counter(int(o) for o in order).items())))
    print("  holds A5 (60) but NOT PSL(2,7) (168 ∤ 120); S5 itself is NOT simple\n")

    # quick lattice census: which non-abelian subgroups does S5 actually hold?
    seen = set()
    names = Counter()
    for k in (1, 2):
        for gens in itertools.combinations(range(size), k):
            H = subgroup_closure(gens, size, mul, inv, ident)
            key = tuple(H)
            if key in seen:
                continue
            seen.add(key)
            names[classify(list(H), size, mul, inv, ident, order)] += 1
    print("  S5 subgroup census (non-abelian):",
          {k: v for k, v in sorted(names.items()) if k not in NONABEL})

    knots = {
        "Conway 11n34  det 1": ([-1, 2, -1, 2, -1, 3, -2, -2, -1, 3, 3], 4),
        "KT 11n42      det 1": ([-1, 2, 2, -3, -3, 2, 1, -2, -2, 3, -2, 3, -2], 4),
        "trefoil 3_1   det 3": ([1, 1, 1], 2),
    }
    for name, (word, n) in knots.items():
        import time
        t0 = time.time()
        by, total = reach(word, n, size, mul, inv, conj, ident, order)
        print(f"\n{name}  total={total}  ({(time.time()-t0):.1f}s)")
        show(by)


if __name__ == "__main__":
    main()
