#!/usr/bin/env python3
"""make_seam_why.py — the seam, one step deeper.

The meridian-order profile (make_seam_profile.py) shows the seam splits in the
order-3 class.  To see *what* the knot groups map onto, classify each
homomorphism by the ORDER of the subgroup of GL(3,2) that is its image.  The
knot group is generated by the strand meridians, so the image is the subgroup
generated by the fixed point's coordinates.

Run:  python3 make_seam_why.py     (n=4 counts ~3 min each)
"""
import time

import numpy as np

from make_gl32_counts import build_GL32, apply_auto
from make_seam_profile import fixed_points


def subgroup_order(elems, mul, inv, ident):
    """Order of the subgroup of G generated by elems (a list of indices)."""
    gen = sorted(set(elems))
    if not gen:
        return 1
    closed = {ident}
    frontier = [ident]
    for g in gen:
        if g not in closed:
            closed.add(g)
            frontier.append(g)
    while frontier:
        a = frontier.pop()
        for b in gen:
            for c in (mul[a, b], mul[b, a], inv[b]):
                if c not in closed:
                    closed.add(c)
                    frontier.append(c)
    return len(closed)


def main():
    size, mul, inv, conj, order = build_GL32()
    ident = int(np.where(order == 1)[0][0])   # the identity element
    print("|GL(3,2)| =", size, " identity idx =", ident)
    knots = {
        "trefoil 3_1": ([1, 1, 1], 2),
        "fig-8 4_1": ([1, -2, 1, -2], 3),
        "Conway 11n34": ([-1, 2, -1, 2, -1, 3, -2, -2, -1, 3, 3], 4),
        "KT 11n42": ([-1, 2, 2, -3, -3, 2, 1, -2, -2, 3, -2, 3, -2], 4),
    }
    for name, (word, n) in knots.items():
        t0 = time.time()
        fps = fixed_points(word, n, size, mul, inv, conj)
        by_order = {}
        nonabel = {}      # homs whose image has order > abelian-floor possibility
        for X in fps:
            so = subgroup_order(list(X), mul, inv, ident)
            by_order[so] = by_order.get(so, 0) + 1
            if so > 1:
                nonabel[so] = nonabel.get(so, 0) + 1
        print(f"\n{name}: total={len(fps)}  ({(time.time()-t0):.1f}s)")
        print("  image order histogram :", dict(sorted(by_order.items())))
        print("  non-trivial images    :", dict(sorted(nonabel.items())))


if __name__ == "__main__":
    main()
