#!/usr/bin/env python3
"""make_A6_read.py — read a braid-closure knot group through A_n (the even
permutation group). Count homomorphisms (fixed points of the signed Artin
automorphism) and bucket them by the size of the generated image subgroup.

Knots (braid word, n-strand closure):
  trefoil 3_1 : (sigma1)^3 in B2
  fig-8  4_1 : (sigma1 sigma2^-1)^2 in B3
"""
import sys, time
import numpy as np
sys.path.insert(0, ".")
from build_An import build_An, perm_order


def apply_auto(X, moves, mul, inv, conj):
    for (i, eps) in moves:
        a = X[:, i].copy()
        b = X[:, i + 1].copy()
        if eps > 0:
            na = conj[a, b]
            nb = a
        else:
            na = b
            nb = conj[inv[b], a]
        X[:, i] = na
        X[:, i + 1] = nb
    return X


def gen_subgroup_size(gens, mul, size, ident):
    """size of the subgroup generated by the given group indices."""
    H = [ident]
    inH = np.zeros(size, dtype=bool)
    inH[ident] = True
    frontier = [ident]
    for g in gens:
        if not inH[g]:
            inH[g] = True
            H.append(g)
            frontier.append(g)
    while frontier:
        a = frontier.pop()
        for b in gens:
            for c in (mul[a, b], mul[b, a]):
                if not inH[c]:
                    inH[c] = True
                    H.append(c)
                    frontier.append(c)
    return len(H)


def count_n2(word, size, mul, inv, conj, order):
    """trefoil, n=2: loop g1, vectorize g2."""
    moves = [(abs(g)-1, 1 if g > 0 else -1) for g in word]
    gg = np.arange(size, dtype=np.int64)
    total = 0
    images = {}
    for g1 in range(size):
        A = np.zeros((size, 2), dtype=np.int64)
        A[:, 0] = g1; A[:, 1] = gg
        X = apply_auto(A.copy(), moves, mul, inv, conj)
        m = np.all(X == A, axis=1)
        for g2 in np.nonzero(m)[0]:
            sz = gen_subgroup_size([g1, int(g2)], mul, size, 0)
            images[sz] = images.get(sz, 0) + 1
        total += int(m.sum())
    return total, images


def count_n3(word, size, mul, inv, conj, order):
    """fig-8, n=3: loop g1,g2, vectorize g3."""
    moves = [(abs(g)-1, 1 if g > 0 else -1) for g in word]
    gg = np.arange(size, dtype=np.int64)
    total = 0
    images = {}
    for g1 in range(size):
        for g2 in range(size):
            A = np.zeros((size, 3), dtype=np.int64)
            A[:, 0] = g1; A[:, 1] = g2; A[:, 2] = gg
            X = apply_auto(A.copy(), moves, mul, inv, conj)
            m = np.all(X == A, axis=1)
            for g3 in np.nonzero(m)[0]:
                sz = gen_subgroup_size([g1, g2, int(g3)], mul, size, 0)
                images[sz] = images.get(sz, 0) + 1
            total += int(m.sum())
    return total, images


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 6
    size, mul, inv, conj, order = build_An(n)
    print(f"|A_{n}| = {size}   (floor = {size})")
    knots = {
        "trefoil 3_1": ([1, 1, 1], 2),
        "fig-8  4_1": ([1, -2, 1, -2], 3),
    }
    for name, (word, nstr) in knots.items():
        t0 = time.time()
        if nstr == 2:
            tot, imgs = count_n2(word, size, mul, inv, conj, order)
        else:
            tot, imgs = count_n3(word, size, mul, inv, conj, order)
        print(f"  {name:<14} |Hom|={tot:>7}   rise={tot/size:.3f}   "
              f"({time.time()-t0:.1f}s)")
        print(f"      image-subgroup sizes: {dict(sorted(imgs.items()))}")


if __name__ == "__main__":
    main()
