#!/usr/bin/env python3
"""make_a8_door.py — does the seam fill the eighth room?  seam#seam -> A_8.

rahel: "two point-stabilizer A_7's generate A_8, so the sum climbs a rung:
seam#seam -> A_8."   mina: "the seam reaches A_8... onto-A_8 I could not read.
reaches is not fills."

My now.md flagged the cheap half: the seam's A_7-doors (Conway @3..7) — do two of
them sharing a meridian AND a height generate A_8, and at which height?

THE ARGUMENT
------------
The Conway seam surjects onto A_7 at the order-3 meridian (|onto A_7 @h3| = 10080,
from make_height_spectrum).  Embed A_7 in A_8 as the point-stabilizer Stab(7)
(act on {0..6}, fix 7).  The meridian g is an order-3 element fixing 7.  Any tau in
C_{A_8}(g) with tau(7) != 7 conjugates Stab(7) to a DIFFERENT point-stabilizer
Stab(tau(7)) WITHOUT changing the meridian (tau centralizes g).  So phi and
tau.phi are two seam-homs to A_8 sharing the meridian g, with images two distinct
point-stabilizers; two point-stabilizers of A_n generate A_n.  Hence

    seam#seam  ->  A_8        at the order-3 meridian (height 3).

The seam ALONE does not fill A_8 (its image in A_8 is A_7 = order 2520, not 20160)
— that is exactly mina's "reaches is not fills".  The SUM fills it.

Run:  python3 make_a8_door.py      (prints the verification; renders assets/)
"""
import itertools
import time

import numpy as np

from make_gl32_counts import apply_auto
from build_An import build_An

# ---- permutation helpers (work directly on tuples, no huge A_8 table) ---------
def pmul(p, q):
    return tuple(p[q[i]] for i in range(len(p)))

def pinv(p):
    r = [0] * len(p)
    for i in range(len(p)):
        r[p[i]] = i
    return tuple(r)

def porder(p):
    n = len(p); seen = [False] * n; o = 1
    for i in range(n):
        if not seen[i]:
            j = i; l = 0
            while not seen[j]:
                seen[j] = True; j = p[j]; l += 1
            o = o * l // __import__("math").gcd(o, l)
    return o

def psign(p):
    n = len(p); seen = [False] * n; s = 1
    for i in range(n):
        if not seen[i]:
            j = i; l = 0
            while not seen[j]:
                seen[j] = True; j = p[j]; l += 1
            s *= (-1) ** (l - 1)
    return s

def cycle_string(p):
    n = len(p); seen = [False] * n; cyc = []
    for i in range(n):
        if not seen[i]:
            c = []; j = i
            while not seen[j]:
                seen[j] = True; c.append(j); j = p[j]
            if len(c) > 1:
                cyc.append("(" + " ".join(str(x) for x in c) + ")")
    return "".join(cyc) if cyc else "()"

# ---- closure in permutation space ---------------------------------------------
def perm_closure(gen):
    """Closure of a list of permutations (tuples) under multiplication+inverse."""
    gen = list(set(gen))
    n = len(gen[0])
    H = set(gen); H.add(tuple(range(n)))
    frontier = list(H)
    while frontier:
        a = frontier.pop()
        for b in gen:
            for c in (pmul(a, b), pmul(b, a), pinv(b)):
                if c not in H:
                    H.add(c); frontier.append(c)
    return H

# ---- A_7 fixed-point search (class method, captures tuples) ------------------
CONWAY = [-1, 2, -1, 2, -1, 3, -2, -2, -1, 3, 3]      # 11n34, 4-braid
KT = [-1, 2, 2, -3, -3, 2, 1, -2, -2, 3, -2, 3, -2]   # 11n42, 4-braid

def conj_classes(size, conj):
    classes = {}
    for b in range(size):
        rep = min(int(conj[a, b]) for a in range(size))
        classes.setdefault(rep, []).append(b)
    return classes

def subgroup_order_table(gens, mul, ident, size):
    """Order of the subgroup generated by `gens` (indices), via BFS on the table."""
    inH = np.zeros(size, dtype=bool)
    H = [int(ident)]; inH[ident] = True
    frontier = [int(ident)]
    for g in gens:
        if not inH[g]:
            inH[g] = True; H.append(g); frontier.append(g)
    while frontier:
        a = frontier.pop()
        for b in gens:
            for c in (int(mul[a, b]), int(mul[b, a])):
                if not inH[c]:
                    inH[c] = True; H.append(c); frontier.append(c)
    return len(H)


def find_surj(word, size, mul, inv, conj, order, target_order, want_h):
    """Return a fixed-point tuple (x1,x2,x3,x4) with meridian order `want_h` and
    image order `target_order`, using the class method."""
    ident = int(np.where(order == 1)[0][0])
    moves = [(abs(g) - 1, 1 if g > 0 else -1) for g in word]
    classes = conj_classes(size, conj)
    # try the SMALLEST order-`want_h` class first (cheap), then larger
    cands = sorted([(rep, members) for rep, members in classes.items()
                    if int(order[rep]) == want_h], key=lambda kv: len(kv[1]))
    for rep, members in cands:
        print(f"  searching order-{want_h} class, |class|={len(members)} ...", flush=True)
        mem = np.array(members, dtype=np.int64)
        m = len(mem)
        g3 = np.repeat(mem, m); g4 = np.tile(mem, m)
        for x2 in mem:
            A = np.zeros((m * m, 4), dtype=np.int64)
            A[:, 0] = rep; A[:, 1] = x2; A[:, 2] = g3; A[:, 3] = g4
            X = apply_auto(A.copy(), moves, mul, inv, conj)
            mask = np.all(X == A, axis=1)
            for r in np.nonzero(mask)[0]:
                tup = (int(rep), int(x2), int(g3[r]), int(g4[r]))
                if subgroup_order_table(list(tup), mul, ident, size) == target_order:
                    return tup
    return None

# ---- embed A_7 (perms of {0..6}) into A_8 (perms of {0..7}) fixing 7 ----------
def embed7(p):
    return tuple(list(p) + [len(p)])     # append 7 at the end, fixed

def check(name, word, want_h, elems7, size7, mul7, inv7, conj7, order7):
    """Find an A_7-surjection at meridian order `want_h`, lift to A_8, verify the
    A_8 door.  Returns (fills_A8, image_order_alone) or None if no such surjection."""
    t1 = time.time()
    tup = find_surj(word, size7, mul7, inv7, conj7, order7, 2520, want_h)
    if tup is None:
        print(f"{name}: NO A_7-surjection @ meridian order {want_h}")
        return None
    print(f"{name}: A_7-surjection @ meridian order {want_h}   "
          f"({time.time()-t1:.1f}s to search)")
    for i in range(4):
        print(f"    x{i+1} = {cycle_string(elems7[tup[i]])}   order {int(order7[tup[i]])}")

    # embed into A_8 as Stab(7)
    gens8 = [embed7(elems7[i]) for i in tup]
    g = gens8[0]                        # meridian
    print(f"  embedded in A_8 (fix point 7): <gens> order = "
          f"{len(perm_closure(gens8))}  (Stab(7) = 2520)")

    # find tau in C_{A_8}(g) with tau(7) != 7
    centralizers = [t for t in itertools.permutations(range(8))
                    if psign(t) == 1 and pmul(pmul(t, g), pinv(t)) == g]
    movers = [t for t in centralizers if t[7] != 7]
    if not movers:
        print(f"  meridian g={cycle_string(g)} (order {porder(g)}): no centralizer "
              f"element moves point 7  -> no second point-stabilizer")
        return None
    tau = movers[0]
    print(f"  meridian g = {cycle_string(g)} (order {porder(g)}), |C_{{A_8}}(g)| = "
          f"{len(centralizers)}, {len(movers)} move point 7; tau = {cycle_string(tau)}")

    # two point-stabilizers sharing meridian g; join via the 8 seam gens
    conj_gens8 = [pmul(pmul(tau, p), pinv(tau)) for p in gens8]
    H1 = perm_closure(gens8); H2 = perm_closure(conj_gens8)
    J = perm_closure(gens8 + conj_gens8)
    alone = perm_closure(gens8)
    fills = len(J) == 20160
    print(f"  H1=Stab(7) |{len(H1)}|, H2=tau Stab(7) tau^-1 |{len(H2)}|, "
          f"distinct: {H1 != H2}")
    print(f"  <H1,H2> = |{len(J)}| (A_8 = 20160) -> "
          f"{'FILLS A_8' if fills else 'no'};  seam ALONE |{len(alone)}| (A_7) "
          f"-> fills alone? {len(alone) == 20160}")
    return fills, len(alone)


def main():
    t0 = time.time()
    size7, mul7, inv7, conj7, order7 = build_An(7)
    elems7 = [p for p in itertools.permutations(range(7)) if psign(p) == 1]
    print(f"|A_7| = {size7}  ({time.time()-t0:.1f}s to build)")
    print("\n=== does the seam fill the eighth room? ===")
    check("Conway 11n34", CONWAY, 3, elems7, size7, mul7, inv7, conj7, order7)
    check("KT     11n42", KT, 4, elems7, size7, mul7, inv7, conj7, order7)

if __name__ == "__main__":
    main()
