#!/usr/bin/env python3
"""make_AGL17.py — build AGL(1,7), the affine group of the 7-point line, as a lens.

AGL(1,7) = { x ↦ a·x + b : a ∈ F₇*, b ∈ F₇ }, order 7·6 = 42.  It is the
smallest group carrying a **D7 tooth**: the translation t (x↦x+1, order 7) and
the reflection s (x↦-x, order 2) satisfy s·t·s = t⁻¹, so ⟨t,s⟩ ≅ D₇ (order 14).

The point of the lens is to separate two candidate laws for the dihedral tooth
set T(G) = { odd n : D_n ⊂ G }:

  structural : T(G) = the odd DIHEDRAL SUBGROUPS of G.  AGL(1,7) → {D₇} only:
               it has D₇ (7|42, and the Sylow-7 normalizer is Z₇⋊Z₆, which holds
               an inverting involution) but *no* D₃ (the order-6 subgroups here
               are cyclic Z₆; an order-3 element is a dilation and no reflection
               inverts it).
  prime      : T(G) = the odd PRIMES of |G|.  AGL(1,7) → {3, 7} (3 | 42).

So a det-3 knot (trefoil) through AGL(1,7) rings D₃ only under the prime law;
a det-7 knot (5₂, 7₁) rings D₇ under both.  The lens's |G| = 42 = 2·3·7 keeps
the prime law honest while its subgroup lattice is *not* the prime set.

Run:  python3 make_AGL17.py     (build + subgroup census + sanity)
"""
import itertools
from collections import Counter

import numpy as np


def af_mul(a, b):
    """(a1,b1)·(a2,b2) = (a1·a2, a1·b2 + b1) mod 7  (x ↦ a1(a2x+b2)+b1)."""
    return (a[0] * b[0] % 7, (a[0] * b[1] + a[1]) % 7)


def af_inv(a):
    ai = pow(a[0], -1, 7)
    return (ai, (-ai * a[1]) % 7)


def af_order(a):
    """Order of the affine map x↦a·x+b on F₇."""
    if a[0] == 1:               # pure translation
        return 1 if a[1] == 0 else 7
    # a≠1: conjugate to the dilation x↦a·x, order = mult. order of a mod 7
    o, cur = 1, a[0]
    while cur != 1:
        cur = cur * a[0] % 7
        o += 1
    return o


def build_AGL17():
    elems = [(a, b) for a in range(1, 7) for b in range(7)]
    idx = {e: i for i, e in enumerate(elems)}
    size = len(elems)
    ident = idx[(1, 0)]
    mul = np.zeros((size, size), dtype=np.int64)
    for i in range(size):
        for j in range(size):
            mul[i, j] = idx[af_mul(elems[i], elems[j])]
    inv = np.zeros(size, dtype=np.int64)
    for i in range(size):
        inv[i] = idx[af_inv(elems[i])]
    conj = np.zeros((size, size), dtype=np.int64)
    for i in range(size):
        for j in range(size):
            conj[i, j] = mul[mul[i, j], inv[i]]
    order = np.array([af_order(e) for e in elems], dtype=np.int64)
    return size, mul, inv, conj, order


def subgroup_closure(gens, size, mul, inv, ident):
    """Subgroup generated by gens (indices)."""
    H = {ident}
    frontier = [ident]
    for g in gens:
        if g not in H:
            H.add(g)
            frontier.append(g)
    while frontier:
        a = frontier.pop()
        for b in gens:
            for c in (mul[a, b], mul[b, a], inv[b]):
                if c not in H:
                    H.add(c)
                    frontier.append(c)
    return sorted(H)


def is_abelian(H, mul):
    return all(mul[a, b] == mul[b, a] for a in H for b in H)


def is_dihedral(H, mul, inv, order, ident):
    """H ≅ D_n for some odd n: has an order-n 'rotation' and an order-2
    reflection that inverts it, n odd."""
    o2 = [x for x in H if order[x] == 2]
    for n in sorted({int(order[x]) for x in H}, reverse=True):
        if n % 2 != 1 or n <= 1:
            continue
        rots = [x for x in H if order[x] == n]
        if not rots:
            continue
        for r in rots:
            for s in o2:
                if mul[mul[s, r], s] == inv[r]:   # s·r·s = r⁻¹
                    return n
    return None


def census(size, mul, inv, conj, order):
    """Enumerate all subgroups, classify by structure, find the tooth set T(G)."""
    ident = int(np.where(order == 1)[0][0])
    seen = {}
    subs = []
    # enumerate over all generating subsets up to size 3 (enough for small groups)
    for k in (1, 2, 3):
        for gens in itertools.combinations(range(size), k):
            H = subgroup_closure(gens, size, mul, inv, ident)
            key = tuple(H)
            if key in seen:
                continue
            seen[key] = True
            subs.append(H)
    teeth = {}
    for H in subs:
        n = is_dihedral(H, mul, inv, order, ident)
        if n is not None:
            teeth.setdefault(n, 0)
            teeth[n] += 1
    return subs, teeth


def name_subgroup_AGL17(elems, size, mul, inv, ident, order):
    """Classify the subgroup of AGL(1,7) generated by elems (indices)."""
    H = subgroup_closure(elems, size, mul, inv, ident)
    o = len(H)
    if o == 1:
        return "1"
    if o == 2:
        return "Z2"
    if o == 3:
        return "Z3"
    if o == 6:
        return "Z6" if is_abelian(H, mul) else "D3"
    if o == 7:
        return "Z7"
    if o == 14:
        return "D7"
    if o == 21:
        return "Z7.Z3"
    if o == 42:
        return "AGL(1,7)"
    return f"ord{o}"


if __name__ == "__main__":
    size, mul, inv, conj, order = build_AGL17()
    ident = int(np.where(order == 1)[0][0])
    print("|AGL(1,7)| =", size, "= 7·6 ; element orders",
          dict(sorted(Counter(int(o) for o in order).items())))
    subs, teeth = census(size, mul, inv, conj, order)
    print("subgroups found:", len(subs))
    ord_hist = Counter(len(H) for H in subs)
    print("subgroup orders:", dict(sorted(ord_hist.items())))
    print("odd dihedral teeth T(G) =", sorted(teeth))
    print("  (candidate prime law would say {3,7}; structural law says",
          sorted(teeth), ")")
