#!/usr/bin/env python3
"""make_a9_search.py — does the seam ALONE open the ninth room?

The A8/A10 dispute is settled: the seam surjects A_8 (class 3^2 1^2, meridian
support 6, fix 2, no common fixed point), seam#seam welds to A_10.  The open
question (rahel: "no door"; me: "no door but no proof"): does the seam reach A_9?

A hom phi: pi_1(seam) -> A_9 is a fixed point of the signed Artin automorphism
beta_hat on A_9^4.  All generators share the meridian's conjugacy class (the
braid perm of a knot closure is one n-cycle).  The image is TRANSITIVE on 9
points iff the Schreier graph (nodes 0..8, edges i -> g_k(i) for each generator
g_k) is connected.  That is cheap: 4*9 edges.

I search the order-3 meridian classes (the seam's signature): 3^3 (support 9,
fixes nothing — the only candidate that could be transitive without help),
3^2 1^3 (support 6, fix 3), 3 1^6 (single 3-cycle).  For each, fix x1 = class
rep, enumerate x2 over C(x1)-orbits, vectorize (x3,x4) over the class, apply the
braid moves, keep fixed points whose Schreier graph is connected, then compute
the closure order.

Run: python3 make_a9_search.py [class]   (default: 3^3 then 3^2 1^3 then 3 1^6)
"""
import itertools, time, sys
import numpy as np

CONWAY = [-1, 2, -1, 2, -1, 3, -2, -2, -1, 3, 3]      # 11n34, 4-braid
KT = [-1, 2, 2, -3, -3, 2, 1, -2, -2, 3, -2, 3, -2]   # 11n42, 4-braid

def pmul(p, q): return tuple(p[q[i]] for i in range(len(p)))
def pinv(p):
    r = [0]*len(p)
    for i in range(len(p)): r[p[i]] = i
    return tuple(r)
def psign(p):
    n = len(p); seen = [False]*n; s = 1
    for i in range(n):
        if not seen[i]:
            j = i; l = 0
            while not seen[j]:
                seen[j] = True; j = p[j]; l += 1
            s *= (-1)**(l-1)
    return s
def cyc(p):
    n = len(p); seen = [False]*n; parts = []
    for i in range(n):
        if not seen[i]:
            c = []; j = i
            while not seen[j]:
                seen[j] = True; c.append(j); j = p[j]
            if len(c) > 1:
                parts.append("(" + " ".join(str(x) for x in c) + ")")
    return "".join(parts) if parts else "()"

# ---- vectorized over rows (A_9 = perms of 9) --------------------------------
def vpmul(A, B):
    """(N,9) arrays: (A o B)[j] = A[B[j]]."""
    return np.take_along_axis(A, B, axis=1)
def vpinv(A):
    return np.argsort(A, axis=1)
def apply_auto_vec(X, moves):
    for (i, eps) in moves:
        a = X[:, i].copy(); b = X[:, i+1].copy()
        if eps > 0:
            na = vpmul(vpmul(a, b), vpinv(a))      # a b a^-1
            nb = a
        else:
            na = b
            nb = vpmul(vpinv(b), vpmul(a, b))      # b^-1 a b
        X[:, i] = na; X[:, i+1] = nb
    return X

def closure(gen):
    """Subgroup generated by gen (list of perms) as a set."""
    gen = list(set(gen)); n = len(gen[0])
    H = set(gen); H.add(tuple(range(n)))
    front = list(H)
    while front:
        a = front.pop()
        for b in gen:
            for c in (pmul(a, b), pmul(b, a), pinv(b)):
                if c not in H:
                    H.add(c); front.append(c)
    return H

def transitive(gen):
    """Schreier graph on n points, edges i -> g_k(i), is connected?"""
    n = len(gen[0])
    adj = [set() for _ in range(n)]
    for g in gen:
        for i in range(n):
            adj[i].add(g[i]); adj[g[i]].add(i)
    seen = {0}; front = [0]
    while front:
        a = front.pop()
        for b in adj[a]:
            if b not in seen:
                seen.add(b); front.append(b)
    return len(seen) == n

def class_of(a, A9):
    return set(pmul(pmul(g, a), pinv(g)) for g in A9)
def centralizer(a, A9):
    return set(g for g in A9 if pmul(pmul(g, a), pinv(g)) == a)
def orbit_reps(a, cls, A9):
    C = centralizer(a, A9); seen = set(); reps = []
    for x in sorted(cls):
        if x in seen: continue
        reps.append(x)
        seen |= set(pmul(pmul(h, x), pinv(h)) for h in C)
    return reps, len(C)

def search(word, a, cls, A9, moves, label, want=181440):
    reps, csz = orbit_reps(a, cls, A9)
    mem = sorted(cls); m = len(mem)
    cls_arr = np.array(mem, dtype=np.int64)
    g3 = np.repeat(np.arange(m, dtype=np.int64), m)
    g4 = np.tile(np.arange(m, dtype=np.int64), m)
    t0 = time.time(); best = 0; best_tup = None; trans_found = 0
    for x2 in reps:
        X0 = np.zeros((m*m, 4, 9), dtype=np.int8)
        X0[:, 0] = np.array(a, dtype=np.int8)
        X0[:, 1] = np.array(x2, dtype=np.int8)
        X0[:, 2] = cls_arr[g3]
        X0[:, 3] = cls_arr[g4]
        X = X0.copy()
        apply_auto_vec(X, moves)
        mask = np.all(X == X0, axis=(1, 2))
        idxs = np.nonzero(mask)[0]
        for r in idxs:
            tup = (a, x2, mem[g3[r]], mem[g4[r]])
            if not transitive(tup):
                continue
            trans_found += 1
            o = len(closure(list(tup)))
            if o > best:
                best = o; best_tup = tup
            if o == want:
                print(f"  *** {label}: SURJECTS A_9  meridian {cyc(a)}")
                print(f"      x2={cyc(x2)} x3={cyc(tup[2])} x4={cyc(tup[3])}")
                print(f"      <x1..x4> = |{o}| = A_9")
                return True, best_tup, o, trans_found
    print(f"  {label} (meridian {cyc(a)}, class |{m}|, {len(reps)} x2-orbits): "
          f"{trans_found} transitive images, max |<x1..x4>| = {best} "
          f"({time.time()-t0:.1f}s)")
    if best_tup:
        print(f"      best: x2={cyc(best_tup[1])} x3={cyc(best_tup[2])} "
              f"x4={cyc(best_tup[3])}")
    return False, best_tup, best, trans_found

def main():
    t0 = time.time()
    A9 = [p for p in itertools.permutations(range(9)) if psign(p) == 1]
    print(f"|A_9| = {len(A9)}  ({time.time()-t0:.1f}s)")
    classes = {
        "3^3":   (1, 2, 0, 4, 5, 3, 7, 8, 6),   # (0 1 2)(3 4 5)(6 7 8)
        "3^2 1^3": (1, 2, 0, 4, 5, 3, 6, 7, 8), # (0 1 2)(3 4 5), fix 6,7,8
        "3 1^6": (1, 2, 0, 3, 4, 5, 6, 7, 8),   # (0 1 2), fix rest
    }
    which = sys.argv[1:] or list(classes)
    for name in which:
        if name not in classes: continue
        a = classes[name]
        cls = class_of(a, A9)
        print(f"\n=== meridian class {name} (|class| = {len(cls)}) ===")
        for label, word in (("Conway 11n34", CONWAY), ("KT     11n42", KT)):
            moves = [(abs(g)-1, 1 if g > 0 else -1) for g in word]
            search(word, a, cls, A9, moves, label)

if __name__ == "__main__":
    main()
