#!/usr/bin/env python3
"""make_knot_reach.py — which SUBGROUPS does each knot surject onto?

The torus rule (make_two_teeth.py) reads a knot by the lens's TEETH — the primes
of |G|.  But that is a *pitch*: it reads the lens's own spectra.  The reach
(make_reach.py) is the other reading — which subgroups the knot's group surjects
onto.  Are those two the same rule, or different?

If the reach were also by teeth, a knot would reach exactly the subgroups with
the right primes, and two knots with the same reach-teeth would reach the same
subgroups.  The no-hand (fig-8) and the trefoil both live in a lens whose teeth
are {2,3,7}.  The trefoil climbs a full ladder (6, 12, 24, 168).  Does the
fig-8?

Run:  python3 make_knot_reach.py
"""
import time

import numpy as np

from make_gl32_counts import build_GL32, apply_auto
from make_seam_profile import fixed_points
from make_seam_why import subgroup_order


def name_subgroup(elems, size, mul, inv, ident, order):
    """Identify the group generated by elems (indices) up to its structure."""
    gen = sorted(set(elems))
    H = {ident}
    frontier = [ident]
    for g in gen:
        if g not in H:
            H.add(g)
            frontier.append(g)
    while frontier:
        a = frontier.pop()
        for b in gen:
            for c in (mul[a, b], mul[b, a], inv[b]):
                if c not in H:
                    H.add(c)
                    frontier.append(c)
    H = sorted(H)
    o = len(H)
    # element-order histogram
    hist = {}
    for x in H:
        hist[order[x]] = hist.get(order[x], 0) + 1
    # abelian?
    abelian = all(mul[a, b] == mul[b, a] for a in H for b in H)
    # classify by order + structure
    if o == 1:
        return "1"
    if o == 2:
        return "Z2"
    if o == 3:
        return "Z3"
    if o == 4:
        return "Z4" if hist.get(4, 0) == 2 else "Z2^2"
    if o == 6:
        return "Z6" if abelian else "S3"
    if o == 7:
        return "Z7"
    if o == 8:
        if abelian:
            return "Z2^3"
        return "D8" if hist.get(4, 0) == 2 else "Q8"
    if o == 12:
        return "Z12" if abelian else ("A4" if hist.get(3, 0) == 8 else "D12")
    if o == 21:
        return "Z7.Z3"
    if o == 24:
        return "S4"
    if o == 168:
        return "GL(3,2)"
    return f"ord{o}"


def reach(word, n, size, mul, inv, conj, ident, order):
    """Return dict: subgroup_name -> (orbits, count)."""
    fps = fixed_points(word, n, size, mul, inv, conj)
    by_sub = {}   # name -> (count, set-of-canonical-image-groups)
    for X in fps:
        so = subgroup_order(list(X), mul, inv, ident)
        if so == 1:
            continue
        nm = name_subgroup(list(X), size, mul, inv, ident, order)
        if nm not in by_sub:
            by_sub[nm] = [0, set()]
        by_sub[nm][0] += 1
        by_sub[nm][1].add(tuple(sorted(set(X))))
    return by_sub


def main():
    size, mul, inv, conj, order = build_GL32()
    ident = int(np.where(order == 1)[0][0])
    print("|GL(3,2)| =", size)

    knots = {
        "3_1 trefoil  (2,3) torus": ([1, 1, 1], 2),
        "4_1 fig-8    no-hand   ": ([1, -2, 1, -2], 3),
        "5_1          (2,5) torus": ([1, 1, 1, 1, 1], 2),
        "5_2": ([1, 2, 2, 2, 1, -2], 3),
        "6_2": ([1, -2, 1, 1, 1, -2], 3),
        "6_3": ([-1, -1, 2, -1, 2, 2], 3),
    }
    for name, (word, n) in knots.items():
        t0 = time.time()
        by_sub = reach(word, n, size, mul, inv, conj, ident, order)
        print(f"\n{name}")
        for nm in sorted(by_sub, key=lambda s: (len(s), s)):
            cnt, grps = by_sub[nm]
            print(f"  reach {nm:<9} count={cnt:>4}  image-groups={len(grps)}")
        print(f"  ({time.time()-t0:.1f}s)")


if __name__ == "__main__":
    main()
