#!/usr/bin/env python3
"""make_psl_seam.py — class-restricted beta-hat-fixed count onto PSL(2,p), table-free.

For a meridian class C (all generators conjugate), count beta-hat-fixed tuples
(x1=rep, x2,x3,x4 in C) for each word, and split them into onto-hands (image =
the whole group) vs the floor (image = the meridian's cyclic group).

The beta-hat-fixed set is diagonal-conjugation-invariant, so x2 ranges over
C(x1)-orbits (rescaling by orbit size) instead of all of C.  C(x1) = <x1>.
This makes |C|^2 x |orbits| the work, so p=37 (|C|=1406) is reachable.
"""
import sys
import time
import numpy as np
from psl import PSL, canon4
import fastkernel

WORDS = {"conway": [-1, 2, -1, 2, -1, 3, -2, -2, -1, 3, 3],
         "kt": [-1, 2, 2, -3, -3, 2, 1, -2, -2, 3, -2, 3, -2]}


def vmm(A, B, p):
    a0, a1, a2, a3 = A[..., 0], A[..., 1], A[..., 2], A[..., 3]
    b0, b1, b2, b3 = B[..., 0], B[..., 1], B[..., 2], B[..., 3]
    return np.stack([(a0 * b0 + a1 * b2) % p, (a0 * b1 + a1 * b3) % p,
                     (a2 * b0 + a3 * b2) % p, (a2 * b1 + a3 * b3) % p], axis=-1)


def vinv(A, p):
    return canon4(np.stack([A[..., 3], (-A[..., 1]) % p,
                            (-A[..., 2]) % p, A[..., 0]], axis=-1), p)


def vconj(a, b, p):
    """matches build_PSL conj[a,b] = a b a^-1."""
    return canon4(vmm(vmm(a, b, p), vinv(a, p), p), p)


def apply_auto(X, moves, p):
    for (i, eps) in moves:
        a = X[:, i, :].copy()
        b = X[:, i + 1, :].copy()
        if eps > 0:
            X[:, i, :] = vconj(a, b, p)
            X[:, i + 1, :] = a
        else:
            X[:, i, :] = b
            X[:, i + 1, :] = vconj(vinv(b, p), a, p)
    return X


def closure_size(gens, G):
    """size of the subgroup generated by gens (canonical reps)."""
    S = {G.id}
    frontier = [G.id]
    while frontier:
        ng = []
        for f in frontier:
            for g in gens:
                h = G.m(f, g)
                if h not in S:
                    S.add(h)
                    ng.append(h)
        frontier = ng
    return len(S)


def orbit_reps_sizes(G, C, T):
    seen = set()
    reps, sizes = [], []
    for y in C:
        if y in seen:
            continue
        orb = {G.cj(y, t) for t in T}
        seen |= orb
        reps.append(y)
        sizes.append(len(orb))
    return reps, sizes


def class_seam(G, rep, C, word, p, verbose=False):
    """Return (n_fixed_x1rep, n_onto_x1rep, n_onto_orbits) for this class/word."""
    moves = [(abs(g) - 1, 1 if g > 0 else -1) for g in word]
    # C(x1) = <x1>
    T = [G.id]
    cur = rep
    while cur != G.id:
        T.append(cur)
        cur = G.m(cur, rep)
    x2reps, x2sizes = orbit_reps_sizes(G, C, T)
    m = len(C)
    # x3,x4 range over C
    mem = np.array(C, dtype=np.int64)  # (m,4)
    g3 = np.repeat(mem, m, axis=0)
    g4 = np.tile(mem, (m, 1))
    rep_arr = np.array(rep, dtype=np.int64)
    tot_fixed = 0
    tot_onto = 0
    for x2, osz in zip(x2reps, x2sizes):
        A = np.zeros((m * m, 4, 4), dtype=np.int64)
        A[:, 0, :] = rep_arr
        A[:, 1, :] = x2
        A[:, 2, :] = g3
        A[:, 3, :] = g4
        F = fastkernel.apply_auto_fast(A.copy(), moves, p)
        mask = np.ones(m * m, dtype=bool)
        for j in range(4):
            out = F[:, j, :]
            inp = A[:, j, :]
            mask &= np.all((out - inp) % p == 0, axis=1) | np.all((out + inp) % p == 0, axis=1)
        n = int(np.count_nonzero(mask))
        tot_fixed += osz * n
        # onto: compute image size for each fixed tuple
        rows = np.nonzero(mask)[0]
        onto = 0
        for r in rows:
            t = (rep, x2, tuple(g3[r]), tuple(g4[r]))
            if closure_size(list(t), G) == G.n:
                onto += 1
        tot_onto += osz * onto
    # onto Inn-orbits: each free onto Inn-orbit contributes |C(x1)|=|T| tuples
    # with x1 = rep, so onto_orbits = tot_onto / |T|.
    onto_orbits = tot_onto // len(T) if len(T) else 0
    return tot_fixed, tot_onto, onto_orbits


def main():
    p = int(sys.argv[1]) if len(sys.argv) > 1 else 13
    t0 = time.time()
    G = PSL(p)
    print(f"|PSL(2,{p})| = {G.n}  (built {time.time()-t0:.1f}s)")
    classes = G.classes()
    # the split-torus class: order (p-1)/2
    target = (p - 1) // 2
    cand = [rep for rep in classes if G.order(rep) == target]
    print(f"  classes of order {target} (split-torus): {len(cand)}")
    results = {}
    for rep in cand:
        C = classes[rep]
        print(f"\n  order {target} class |C|={len(C)}:")
        for name, word in WORDS.items():
            nf, no, noo = class_seam(G, rep, C, word, p)
            results[(name, rep)] = (nf, no, noo)
            print(f"    {name:6s}: fixed(x1=rep)={nf:7d}  onto(x1=rep)={no:6d}  onto-orbits={noo:5d}")
    # seam report
    print("\n  seam (Conway vs KT onto-orbits):")
    for rep in cand:
        c = results.get(("conway", rep))
        k = results.get(("kt", rep))
        if c and k:
            d = c[2] - k[2]
            print(f"    order {G.order(rep)} class: Conway {c[2]} vs KT {k[2]}  diff {d}  {'<-- SEAM' if d else ''}")


if __name__ == "__main__":
    main()
