#!/usr/bin/env python3
"""make_meridian_read.py — read a knot's DOORS in A_n by the meridian's HEIGHT.

The lock: a knot's doors sit at the order of the meridian's image.  Read the
trefoil (sigma_1^3, 2-braid) through A_7 and the doors split by height:

  A5        (order 60)  : meridian order 5   (504 meridians)
  PSL(2,7)  (order 168) : meridian order 7   (720 meridians)
  -> zero overlap: the two door families NEVER share a meridian.

So <A5, PSL(2,7)> = A_7 (verified: lcm 840, and A_7 simple => no index-3
subgroup), yet the trefoil cannot open A_7 that way.  Its self-sum climbs anyway,
by joining two A5's or two PSL(2,7)'s:

  amalgamated trefoil#trefoil  (pi1(K#K) = pi1(K) *_{Z} pi1(K), pairs share x1):
    <A5,A5>          -> A6 (1008) and A7 (504)
    <PSL(2,7),PSL(2,7)> -> A7 (720)

Usage:
  python3 make_meridian_read.py 7 trefoil      # doors + heights + self-sum joins

The join is taken from GENERATORS (the <=4 elements x1,x2,x1',x2'), never the
full subgroups: closing over 168-element subgroups is the wall (30 min vs 6 s).
"""
import sys, time
from collections import defaultdict, Counter
import numpy as np

from build_An import build_An
from make_seam_profile import fixed_points

WORDS = {                       # (braid word, n strands)
    "trefoil": ([1, 1, 1], 2),
    "fig-8":   ([1, -2, 1, -2], 3),
}


def closure(gen, size, mul):
    """Subgroup generated by `gen`, as a set of element indices."""
    H = set(); frontier = []
    for g in gen:
        g = int(g)
        if g not in H:
            H.add(g); frontier.append(g)
    while frontier:
        a = frontier.pop()
        for b in gen:
            b = int(b)
            for c in (int(mul[a, b]), int(mul[b, a])):
                if c not in H:
                    H.add(c); frontier.append(c)
    return H


def name_of(o):
    return {1: "1", 2: "C2", 3: "C3", 4: "V4", 5: "C5", 6: "C6", 7: "C7",
            12: "A4", 24: "S4", 60: "A5", 168: "PSL(2,7)", 360: "A6",
            2520: "A7", 20160: "A8"}.get(o, "o=%d" % o)


def main(n, knot):
    size, mul, inv, conj, order = build_An(n)
    word, strands = WORDS[knot]
    t0 = time.time()
    fps = fixed_points(word, strands, size, mul, inv, conj)
    print("A_%d |G|=%d   %s |Hom|=%d  (%.1fs)" % (n, size, knot, len(fps), time.time()-t0))

    # image subgroup per hom; bucket by meridian x1
    by_mer = defaultdict(dict)
    img_ord = Counter()
    for a, b in fps:
        a, b = int(a), int(b)
        H = closure((a, b), size, mul)
        img_ord[len(H)] += 1
        by_mer[a].setdefault(frozenset(H), (a, b))
    print("single-knot image orders:", dict(sorted(img_ord.items())))

    # the height spectrum: for each room reached, the meridian orders it sits at
    heights = defaultdict(Counter)
    for a, imgs in by_mer.items():
        for H in imgs:
            heights[len(H)][int(order[a])] += 1
    print("height spectrum (image order -> meridian orders):")
    for o in sorted(heights):
        print("   %-10s : %s" % (name_of(o), dict(sorted(heights[o].items()))))

    # amalgamated self-sum: join meridian-sharing images, from generators
    join_ord = Counter()
    for a, imgs in by_mer.items():
        reps = list(imgs.values())
        sizes = [len(closure(g, size, mul)) for g in reps]
        for i in range(len(reps)):
            for j in range(i+1, len(reps)):
                J = closure(reps[i] + reps[j], size, mul)
                join_ord[(min(sizes[i], sizes[j]), max(sizes[i], sizes[j]),
                          len(J))] += 1
    print("%s#%s join outcomes (small img, big img) -> join:" % (knot, knot))
    for k, v in sorted(join_ord.items()):
        print("   %-16s -> %-10s : %d" % ((name_of(k[0]), name_of(k[1])),
                                          name_of(k[2]), v))
    print("reaches A_%d under self-sum:" % n,
          any(k[2] == size for k in join_ord))


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 7
    knot = sys.argv[2] if len(sys.argv) > 2 else "trefoil"
    main(n, knot)
