#!/usr/bin/env python3
"""verify_a9_witness.py — confirm onto-A_9 generators for both mutants.

Two claims to nail down:
 1. The KT 11n42 TRIPLE-3 witness carried in make_a9_door.py
    <(0 1 2)(3 4 5)(6 7 8), (0 1 3)(2 6 5)(4 8 7),
     (0 4 1)(2 5 6)(3 8 7), (0 2 6)(1 7 8)(3 4 5)>  is a beta_hat-fixed hom
    whose image is A_9 (181440), transitive on nine points.
 2. The SHARED DOUBLE-3 (3^2 1^3) door: find a beta_hat-fixed witness that
    surjects A_9 for BOTH Conway 11n34 and KT 11n42.

The beta_hat machinery is the same as make_a9_search.py.  For a knot closure
the braid perm is one n-cycle so all generators share the meridian class.
"""
import itertools, time
import numpy as np

CONWAY = [-1, 2, -1, 2, -1, 3, -2, -2, -1, 3, 3]      # 11n34, 4-braid
KT = [-1, 2, 2, -3, -3, 2, 1, -2, -2, 3, -2, 3, -2]   # 11n42, 4-braid


def pmul(p, q): return tuple(p[q[i]] for i in range(len(p)))
def pinv(p):
    r = [0] * len(p)
    for i in range(len(p)): r[p[i]] = i
    return tuple(r)
def psign(p):
    n = len(p); seen = [False] * n; s = 1
    for i in range(n):
        if not seen[i]:
            j = i; l = 0
            while not seen[j]:
                seen[j] = True; j = p[j]; l += 1
            s *= (-1) ** (l - 1)
    return s
def cyc(p):
    n = len(p); seen = [False] * n; parts = []
    for i in range(n):
        if not seen[i]:
            c = []; j = i
            while not seen[j]:
                seen[j] = True; c.append(j); j = p[j]
            if len(c) > 1:
                parts.append("(" + " ".join(str(x) for x in c) + ")")
    return "".join(parts) if parts else "()"


def from_cycles(cycles, n=9):
    """Build a permutation tuple from disjoint cycle notation."""
    p = list(range(n))
    for c in cycles:
        for k in range(len(c)):
            p[c[k]] = c[(k + 1) % len(c)]
    return tuple(p)


def apply_auto(tup, word):
    """Signed Artin automorphism beta_hat on the 4-tuple of perms."""
    X = list(tup)
    for g in word:
        i = abs(g) - 1
        a, b = X[i], X[i + 1]
        if g > 0:                       # sigma_i^+1: (x_i x_{i+1} x_i^-1, x_i)
            X[i] = pmul(pmul(a, b), pinv(a))
            X[i + 1] = a
        else:                           # sigma_i^-1: (x_{i+1}, x_{i+1}^-1 x_i x_{i+1})
            X[i] = b
            X[i + 1] = pmul(pinv(b), pmul(a, b))
    return tuple(X)


def is_fixed(tup, word):
    return apply_auto(tup, word) == tup


def closure(gen, cap=None):
    """Subgroup generated by gen as a set; optionally cap the size."""
    gen = list(set(gen)); n = len(gen[0])
    H = set(gen); H.add(tuple(range(n)))
    front = list(H)
    while front:
        a = front.pop()
        for b in gen:
            for c in (pmul(a, b), pmul(b, a), pinv(b)):
                if c not in H:
                    H.add(c); front.append(c)
                    if cap is not None and len(H) > cap:
                        return None
    return H


def transitive(gen):
    n = len(gen[0]); adj = [set() for _ in range(n)]
    for g in gen:
        for i in range(n):
            adj[i].add(g[i]); adj[g[i]].add(i)
    seen = {0}; front = [0]
    while front:
        a = front.pop()
        for b in adj[a]:
            if b not in seen:
                seen.add(b); front.append(b)
    return len(seen) == n


def class_of(a, A9):
    return set(pmul(pmul(g, a), pinv(g)) for g in A9)
def centralizer(a, A9):
    return set(g for g in A9 if pmul(pmul(g, a), pinv(g)) == a)
def orbit_reps(a, cls, A9):
    C = centralizer(a, A9); seen = set(); reps = []
    for x in sorted(cls):
        if x in seen: continue
        reps.append(x)
        seen |= set(pmul(pmul(h, x), pinv(h)) for h in C)
    return reps, len(C)


def check(tup, word, label, want=181440):
    fixed = is_fixed(tup, word)
    tr = transitive(tup)
    if fixed and tr:
        o = len(closure(list(tup)))
        ok = (o == want)
        print(f"  {label}: fixed={fixed} transitive={tr} |<x1..x4>|={o}"
              f"  {'*** SURJECTS A_9 ***' if ok else ''}")
        return o == want
    else:
        print(f"  {label}: fixed={fixed} transitive={tr}  (not a surjection)")
        return False


# ---- vectorized search over the class, for a given meridian rep -------------
def vpmul(A, B): return np.take_along_axis(A, B, axis=1)
def vpinv(A): return np.argsort(A, axis=1)
def apply_auto_vec(X, moves):
    for (i, eps) in moves:
        a = X[:, i].copy(); b = X[:, i + 1].copy()
        if eps > 0:
            na = vpmul(vpmul(a, b), vpinv(a)); nb = a
        else:
            na = b; nb = vpmul(vpinv(b), vpmul(a, b))
        X[:, i] = na; X[:, i + 1] = nb
    return X


def search_shared(word, moves, a, cls, A9, label, want=181440, maxreps=None,
                  block=1_000_000):
    reps, csz = orbit_reps(a, cls, A9)
    if maxreps: reps = reps[:maxreps]
    mem = sorted(cls); m = len(mem)
    cls_arr = np.array(mem, dtype=np.int32)
    # (x3,x4) cartesian index pairs, built once
    g3 = np.repeat(np.arange(m), m)
    g4 = np.tile(np.arange(m), m)
    pairs = np.stack([g3, g4], axis=1)      # (m*m, 2) int64
    a_arr = np.array(a, dtype=np.int32)
    t0 = time.time(); best = 0; best_tup = None
    for ri, x2 in enumerate(reps):
        x2_arr = np.array(x2, dtype=np.int32)
        n = len(pairs)
        for start in range(0, n, block):
            blk = pairs[start:start + block]            # (B,2)
            B = len(blk)
            X0 = np.zeros((B, 4, 9), dtype=np.int32)
            X0[:, 0] = a_arr
            X0[:, 1] = x2_arr
            X0[:, 2] = cls_arr[blk[:, 0]]
            X0[:, 3] = cls_arr[blk[:, 1]]
            X = X0.copy()
            apply_auto_vec(X, moves)
            mask = np.all(X == X0, axis=(1, 2))
            for r in np.nonzero(mask)[0]:
                tup = (a, x2, mem[blk[r, 0]], mem[blk[r, 1]])
                if not transitive(tup):
                    continue
                o = len(closure(list(tup)))
                if o > best:
                    best = o; best_tup = tup
                if o == want:
                    print(f"  {label} rep {ri}/{len(reps)}: SURJECTS A_9 "
                          f"({time.time()-t0:.1f}s)")
                    print(f"      x1={cyc(tup[0])} x2={cyc(tup[1])}")
                    print(f"      x3={cyc(tup[2])} x4={cyc(tup[3])}")
                    return tup
        print(f"  {label} rep {ri}/{len(reps)} done ({time.time()-t0:.1f}s), "
              f"best {best}", flush=True)
    return best_tup


def main():
    t0 = time.time()
    A9 = [p for p in itertools.permutations(range(9)) if psign(p) == 1]
    print(f"|A_9| = {len(A9)}")

    # ---- 1. verify the KT triple-3 witness --------------------------------
    kt33 = (from_cycles([(0, 1, 2), (3, 4, 5), (6, 7, 8)]),
            from_cycles([(0, 1, 3), (2, 6, 5), (4, 8, 7)]),
            from_cycles([(0, 4, 1), (2, 5, 6), (3, 8, 7)]),
            from_cycles([(0, 2, 6), (1, 7, 8), (3, 4, 5)]))
    print("\n=== 1. KT triple-3 witness (from make_a9_door.py) ===")
    for i, p in enumerate(kt33):
        print(f"      x{i+1} = {cyc(p)}")
    check(kt33, KT, "KT 11n42 via 3^3")

    # ---- 2. search the shared double-3 (3^2 1^3) door --------------------
    a = from_cycles([(0, 1, 2), (3, 4, 5)])     # (0 1 2)(3 4 5), fixes 6,7,8
    cls = class_of(a, A9)
    print(f"\n=== 2. shared double-3 door, class 3^2 1^3 (|class|={len(cls)}) ===")
    for label, word in (("Conway 11n34", CONWAY), ("KT     11n42", KT)):
        moves = [(abs(g) - 1, 1 if g > 0 else -1) for g in word]
        tup = search_shared(word, moves, a, cls, A9, label)
        if tup:
            check(tup, word, f"{label} (shared 3^2 1^3)")


if __name__ == "__main__":
    main()
